#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

if [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    if scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~; then
        echo "File transferred successfully to $3@$2:~/"
    else
        echo "Failed to transfer file to $3@$2:~/"
        exit 1
    fi
fi
