#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing Nginx
# Nginx should be listening on port 80 and serving a "Hello World" page

set -euo pipefail

echo "Updating and installing Nginx..."
sudo apt-get update -y -qq
sudo apt-get install nginx -y

echo "Setting up Nginx..."
sudo service nginx start

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Backup default index file
sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bak

# Serve a "Hello World" page
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html >/dev/null

# Configure redirection
sudo sed -i.bak '/server_name _;/a \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Configure custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html >/dev/null
sudo sed -i.bak '/server_name _;/a \\terror_page 404 /error_404.html;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart

echo "Nginx installation and configuration completed."
