#!/usr/bin/env bash
# This script demonstrates handling signals and creating a PID file

PRID=$$
echo "$PRID" > /var/run/myscript.pid


cleanup() {
echo "Cleaning up and exiting..."
rm -f "$pid_file"
exit 0
}


sigterm_handler() {
echo "I hate the kill command"
}


sigint_handler() {
echo "Y U no love me?!"
}


trap 'sigterm_handler' TERM
trap 'sigint_handler' INT
trap 'cleanup' QUIT


echo $$ > "$pid_file"


while :
do
echo "To infinity and beyond"
sleep 2
done
