#!/usr/bin/env bash
# This script demonstrates handling signals and creating a PID file

PRID=$$
echo "$PRID" > /var/run/myscript.pid

# Function to clean up and exit
cleanup() {
echo "Cleaning up and exiting..."
rm -f "$pid_file"
exit 0
}

# Function to handle SIGTERM signal
sigterm_handler() {
echo "I hate the kill command"
}

# Function to handle SIGINT signal
sigint_handler() {
echo "Y U no love me?!"
}

# Trap signals
trap 'sigterm_handler' TERM
trap 'sigint_handler' INT
trap 'cleanup' QUIT

# Create PID file
echo $$ > "$pid_file"

# Display message indefinitely
while true
do
echo "To infinity and beyond"
sleep 1
done
